# SQL Interview Questions  - Quiz

## Introduction

In this lesson, we'll go through a short quiz containing the types of questions about SQL and relational databases that you can expect to see in an interview. 



## SQL Interview Questions

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

what are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________
1. Text
2. Numeric
3. Real
4. Blob

No you cant. 




## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Primary keys are the values contained in a table column that uniquely identify each record in that table. A table cannot have two primary keys with the same value. A foreign key is a value in another table that refers to a primary key in a different table. 




## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:

one to one: each record in the first table refers to only one record in the second table

One to many: Each record in the first database is found multiple times in a second database (but each record in the second database relates to only one record in the first database)

many to many: a value in the first table can refer to multiple values in the second table, and vice versa. 

foreign keys: values in a table that are actually the primary keys of another table


_______________________________________________________________________________________________________________________________


## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:

INNER JOIN: returns only those records in the joining column found in both tables
LEFT JOIN: ONly returns records from the second table if they exist in the first table, while keeping all records in the left table. all records in left table having no correspondeing entries in the second will have NaN values in the new columns. 
OUTER JOIN: Returns records from both tables. NaN values imputed for missing entries. 
_______________________________________________________________________________________________________________________________



## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:

GROUP BY allows us to return a new table which has only the uniques values in the column we specify as the GROUP BY parameter. 

Aggregate functions tell SQL how to condense other values in the same rows as the duplicate values of the GROUP BY column. 
_______________________________________________________________________________________________________________________________



## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:

THey serve as intermediary tables that that list every co-occurence of values from the JOIN columns in both tables. 
_______________________________________________________________________________________________________________________________



## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.