# SQL Interview Questions  - Quiz

## Introduction

In this lesson, we'll go through a short quiz containing the types of questions about SQL and relational databases that you can expect to see in an interview. 



## SQL Interview Questions

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

what are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
______________

1) TEXT: Any alphanumberic characters that represent plain text (e.g., your name, a paragraph, email address).
2) INTEGER: A whole number that contains no letter(s), special characters or decimal points
3) REAL: Any decimal like number
4) BLOB: Datatype used for holding binary data. The value is a blob of data, stored exactly as it was input.
_________________________________________________________________________________________________________________



## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Primary and Foreign Keys each components of a table.  A Primary Key are columns in a table that uniquely identify a row.  Foreign Keys are not primary keys in a table, but are for another table.  Both Primary and Foreign Keys can be used to join tables.




## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
The different types of relationships entities can have in SQL databases are one-to-one, one-to-many, and many-to-many. One-to-one is self-explanatory--each record in the table is linked to one, and only one, record in a different corresponding table. An example of a one-to-many relationship would be a Class table and a Student table that we could use to store a class roster. Since one class can have many students, this would be a one-to-many relationship, that would created by giving the Student records a foreign key column that would reference the primary key of the class they are enrolled in.

Many-to-Many relationships are more complex, because we can have an arbitrary number of records on either side of the relationship.

## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
1) LEFT/RIGHT JOIN: returns all records from the left/right table and the matched records from the right/left table.  If the result is NULL from the right/left table there is no match.
2) INNER JOIN: returns only the overlapping data where a key from one table matched a key from the other table.
3) OUTER JOIN: returns only the data where there is no match between the two tables


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Aggregate functions are used to calculate something (e.g., SUM, AVG, COUNT, MEAN, etc) based on a defined GROUP. The GROUP BY statements are used to aggregate/group data and can be a group by one or more columns.  Commonly, GROUP BY involves an Aggregate Function.


## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________

Associative Entities, (e.g., JOIN Tables), are a type of table used to perform many-to-many JOINs. These tables act as a list that keep track of each of the different connections between an entity in one table and all of that entity's connections in another table. While we can JOIN tables directly for one-to-one and one-to-many relationships, we must use an Associative Entity in order to pull of a JOIN between two tables with a many-to-many relationship.

## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.